from setuptools import setup, find_packages

setup(
    name="shuwaemon-news-generator",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "fastapi>=0.110.0",
        "uvicorn>=0.28.0",
        "jinja2>=3.1.3",
        "python-multipart>=0.0.9",
        "python-dotenv>=1.0.1",
        "google-generativeai>=0.3.2",
        "google-api-python-client>=2.118.0",
        "pandas>=2.2.0",
        "openpyxl>=3.1.2",
        "pytest>=7.4.0",
        "httpx>=0.25.0",
        "openai>=1.0.0",
        "anthropic>=0.7.0",
    ],
    python_requires=">=3.8",
    author="Makoto World",
    author_email="your-email@example.com",
    description="しゅわえもんニュース生成システム",
    keywords="news, generation, AI, Google Gemini",
    url="https://github.com/yourusername/shuwaemon-news-generator",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    package_data={
        "": ["*.txt", "*.md", "*.yml", "*.yaml", "*.json"],
    },
)
